name: Build, Test, and Deploy

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install
      uses: bahmutov/npm-install@v1

    - name: Build
      run: |
        npm run build --if-present
      env:
        CI: true

    - name: Test
      run: |
        npm run ci --if-present
      env:
        CI: true

    - name: Audit
      run: |
        npm run audit --if-present
      env:
        CI: true

    - name: Prepare and deploy
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run docs --if-present
      if: ${{ github.ref == 'refs/heads/main' }}
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}